### PR TITLE
Add support for handling orders created via old Billmate plugin

### PR DESCRIPTION
**Pull request by NiklasHogefjord**
* _Cancel_ payment is now available for the following payment method id's: _bco_ (new Billmate Checkout plugin), _billmate_checkout_, _billmate_partpayment_, _billmate_cardpay_ & _billmate_invoice_
* _Activate_ payment is now available for the following payment method id's: _bco_ (unless payment  16, 24 & 32), _billmate_checkout_ (unless for Billmate Checkout (Direktbetalning) & Billmate Checkout (Swish)), _billmate_invoice_ & _billmate_partpayment_.

### Admin notice
If both _Billmate Payment Gateway for WooCommerce_ and _Billmate Order Management for WooCommerce_ plugin are activated and the following criterias are met:
* Billmate Checkout for WooCommerce payment method is enabled in settings.
* Activation and/or cancelation of orders are activated in _Billmate Order Management for WooCommerce_ plugin.
* Activation and/or cancelation of orders are activated in _Billmate Payment Gateway for WooCommerce_ plugin.

Then the following admin notice is displayed for the merchant:

image

This admin notice will not be removed/closed until order management is deactivated in one of the two plugins or the old Billmate plugin is deactivated.

### CODE REVIEW

**Comment by NiklasHogefjord** [comment]
Handling refunds for payments created in the old Billmate plugin from Billmate Order Management plugin is sadly not possible.

**Comment by andyjohansson** [comment]
We need to add translations before we approve this pull request.

**Comment by andyjohansson** [comment]
@stefanliden will add the translations.

**Comment by MattiasNilsson** [comment]
@NiklasHogefjord @stefanliden Have the Swedish translations been added to this yet?

**Comment by NiklasHogefjord** [comment]
Not yet. @stefanliden wanted to do another change before it was ready for release.

**Pull request merged**
